//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpreendedorismoEIT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmpreendedorismoEIT.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse tipo de arquivo não é válido.
        /// </summary>
        public static string ErrAllowedExtensions {
            get {
                return ResourceManager.GetString("ErrAllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível alterar a senha. Tente novamente..
        /// </summary>
        public static string ErrAlterarSenha {
            get {
                return ResourceManager.GetString("ErrAlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano inválido.
        /// </summary>
        public static string ErrAno {
            get {
                return ResourceManager.GetString("ErrAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a adição. Tente novamente mais tarde..
        /// </summary>
        public static string ErrCreate {
            get {
                return ResourceManager.GetString("ErrCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível adicionar o usuário. Tente novamente..
        /// </summary>
        public static string ErrCreateUsuario {
            get {
                return ResourceManager.GetString("ErrCreateUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a exclusão. Tente novamente mais tarde..
        /// </summary>
        public static string ErrDelete {
            get {
                return ResourceManager.GetString("ErrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir o usuário. Tente novamente..
        /// </summary>
        public static string ErrDeleteUsuario {
            get {
                return ResourceManager.GetString("ErrDeleteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email inválido.
        /// </summary>
        public static string ErrEmail {
            get {
                return ResourceManager.GetString("ErrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especifique o instituto ou faculdade.
        /// </summary>
        public static string ErrInstituto {
            get {
                return ResourceManager.GetString("ErrInstituto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um logotipo para a empresa.
        /// </summary>
        public static string ErrLogotipo {
            get {
                return ResourceManager.GetString("ErrLogotipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho máximo permitido é de {0}MB.
        /// </summary>
        public static string ErrMaxFileSize {
            get {
                return ResourceManager.GetString("ErrMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Não informado].
        /// </summary>
        public static string ErrNull {
            get {
                return ResourceManager.GetString("ErrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL não corresponde à rede social.
        /// </summary>
        public static string ErrSite {
            get {
                return ResourceManager.GetString("ErrSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve incluir o DDD.
        /// </summary>
        public static string ErrTelefone {
            get {
                return ResourceManager.GetString("ErrTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a atualização. Tente novamente mais tarde..
        /// </summary>
        public static string ErrUpdate {
            get {
                return ResourceManager.GetString("ErrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL inválida.
        /// </summary>
        public static string ErrURL {
            get {
                return ResourceManager.GetString("ErrURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário já existe..
        /// </summary>
        public static string ErrUsuarioDuplicado {
            get {
                return ResourceManager.GetString("ErrUsuarioDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira apenas números.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada inválida.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo precisa ser preenchido.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso..
        /// </summary>
        public static string SucAlterarSenha {
            get {
                return ResourceManager.GetString("SucAlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário adicionado com sucesso..
        /// </summary>
        public static string SucCreateUsuario {
            get {
                return ResourceManager.GetString("SucCreateUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluído com sucesso..
        /// </summary>
        public static string SucDeleteUsuario {
            get {
                return ResourceManager.GetString("SucDeleteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho inválido.
        /// </summary>
        public static string Tamanho {
            get {
                return ResourceManager.GetString("Tamanho", resourceCulture);
            }
        }
    }
}
